# Generated by Django 5.2.3 on 2025-06-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_tag_rename_pinned_note_is_pinned_note_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_pinned',
            new_name='pinned',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
    ]
